## LESSON - 1  Tensors

- Tensors are specialized data structures similar to arrays and matrices. They are almost like numpy arrays, except they can run in GPU or other hardware accelarators(TPU).

In [55]:
import torch 
import numpy as np

# 1. `Directly from data`

In [56]:
data = [[1,2,3], [4,5,6]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2, 3],
        [4, 5, 6]])


# 2. `From a Numpy array`

In [57]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2, 3],
        [4, 5, 6]])


# 3. `From Another Tensors`

In [58]:
x_ones = torch.ones_like(x_data)  # retains the property of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1, 1],
        [1, 1, 1]]) 

Random Tensor: 
 tensor([[0.7459, 0.6502, 0.8230],
        [0.4077, 0.0247, 0.4284]]) 



# 4. `With Random or Constant Values`

In [59]:
shape = (2,3,2)     # 3x2 shape and 2 is batch size 
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[[0.3141, 0.5546],
         [0.4442, 0.6329],
         [0.9102, 0.1334]],

        [[0.1368, 0.5034],
         [0.5084, 0.0671],
         [0.8321, 0.1587]]]) 

Ones Tensor: 
 tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]]) 

Zeros Tensor: 
 tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]) 



# 5. `Attribute of a Tensor`

- Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [60]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype:}")
print(f"Device tensor is stored on: {tensor.device:}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# 6. `Operations on Tensors`

- Over 100 tensor oprations; arithmetic, linear algebra, matrix manipulation(transpose, indexing, slicing) sampling and more. Each operation can run on GPU(higher speed) and CPU(lower speed). By default tensors are created on CPU.
- Explicitly move tensors to GPU using `.to` method(after checking the availability).

In [61]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

1. `standard numpy like indexing and slicing`

In [62]:
tensor = torch.ones(4,4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[...,-1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


2. `Joining Tensor` using `torch.cat` 

In [63]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


3. `Arithmetic Operations`

In [64]:
# This computed the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` return the transpose fo a tensor


y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

# This computes the element-wise product, z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
print(torch.mul(tensor, tensor, out=z3))

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


`Single Element Tensor`

In [65]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


`In-Place operations` Operations that store the result into the o

In [66]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


# 7. `Bridge with Numpy` 

- `Tensor to numpy array`

In [70]:
t = torch.ones(5)
print(f"t:{t}")
n = t.numpy()
print(f"n: {n}")

t:tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


# what we learned

- we learned how to create tensors from data, how to convert numpy arrays into tensors.
- create new similar tensors from another tensors >> using `.ones_like`, `rand_like` etc.
- create tensors with random or constant values >> using `.rand`, `.ones`, `zeros` 
- attributes of tensors >> `.shape`, `.dtype`, `.device`
- operations done on tensors >> `cat`, `matmul`, `mul` etc.
- bridge with numpy >> how to convert tensors to numpy arrays 